# Change these first
owner: tp-link-extender # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: Heliodex

sites:
  - name: Mercury
    url: https://mercs.dev
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: Client setup
    url: https://setup.mercs.dev
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: Orbiter
    url: https://gs.mercs.dev
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
    expectedStatusCodes:
      - 404

assignees:
  - Heliodex

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mercs.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  name: Mercury
  introTitle: "Mercury status"
  navbar:
    - title: Mercury
      href: https://mercs.dev
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: "[Mercury](https://mercs.dev). This page is [open source]($REPO)."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
